controller_list:
  - name: jaco_arm_controller
    action_ns: jaco_joint_position_controller
    type: position_controllers/JointPositionController
    joints:
      - jaco_joint_1
      - jaco_joint_2
      - jaco_joint_3
      - jaco_joint_4
      - jaco_joint_5
      - jaco_joint_6
  - name: jaco__hand_controller
    action_ns: jaco_joint_position_controller
    type: position_controllers/JointPositionController
    joints:
      - jaco_joint_6
      - jaco_joint_finger_1
      - jaco_joint_finger_tip_1
      - jaco_joint_finger_2
      - jaco_joint_finger_tip_2
      - jaco_joint_finger_3
      - jaco_joint_finger_tip_3