# MoveIt-specific simulation settings
moveit_sim_hw_interface:
  joint_model_group: controllers_initial_group_
  joint_model_group_pose: controllers_initial_pose_
# Settings for ros_control control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - jaco_joint_1
    - jaco_joint_2
    - jaco_joint_3
    - jaco_joint_4
    - jaco_joint_5
    - jaco_joint_6
    - jaco_joint_finger_1
    - jaco_joint_finger_tip_1
    - jaco_joint_finger_2
    - jaco_joint_finger_tip_2
    - jaco_joint_finger_3
    - jaco_joint_finger_tip_3
  sim_control_mode: 0  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  []
jaco_position_controller:
  type: position_controllers/JointPositionController
  joints:
    - jaco_joint_1
    - jaco_joint_2
    - jaco_joint_3
    - jaco_joint_4
    - jaco_joint_5
    - jaco_joint_6
  gains:
    jaco_joint_1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    jaco_joint_2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    jaco_joint_3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    jaco_joint_4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    jaco_joint_5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    jaco_joint_6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1