controller_list:
  - name: jaco
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - jaco_joint_1
      - jaco_joint_2
      - jaco_joint_3
      - jaco_joint_4
      - jaco_joint_5
      - jaco_joint_6
  - name: jaco_hand
    action_ns: hand_command
    type: GripperCommand
    default: true    
    joints:
      - jaco_joint_finger_1
      - jaco_joint_finger_2
      - jaco_joint_finger_3